const patchData = [
  {
    "userNo": "1",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.1",
    "legend": "BEAM 01",
    "location": "Fixtures, 1.004",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "2",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.19",
    "legend": "BEAM 02",
    "location": "Fixtures, 1.006",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "14"
  },
  {
    "userNo": "3",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.37",
    "legend": "BEAM 03",
    "location": "Fixtures, 1.009",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "14"
  },
  {
    "userNo": "4",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.55",
    "legend": "BEAM 04",
    "location": "Fixtures, 1.011",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "5",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.73",
    "legend": "BEAM 05",
    "location": "Fixtures, 1.019",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "6",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.91",
    "legend": "BEAM 06",
    "location": "Fixtures, 1.021",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "14"
  },
  {
    "userNo": "7",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.109",
    "legend": "BEAM 07",
    "location": "Fixtures, 1.022",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "14"
  },
  {
    "userNo": "8",
    "fixture": "LuminaBeam300 (User)",
    "mode": "18CH",
    "address": "1.127",
    "legend": "BEAM 08",
    "location": "Fixtures, 1.024",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "9",
    "fixture": "A.leda B-EYE K10",
    "mode": "Shapes",
    "address": "1.145",
    "legend": "WASH 01",
    "location": "Fixtures, 1.005",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "10",
    "fixture": "A.leda B-EYE K10",
    "mode": "Shapes",
    "address": "1.180",
    "legend": "WASH 02",
    "location": "Fixtures, 1.007",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "11",
    "fixture": "A.leda B-EYE K10",
    "mode": "Shapes",
    "address": "1.215",
    "legend": "WASH 03",
    "location": "Fixtures, 1.008",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "12",
    "fixture": "A.leda B-EYE K10",
    "mode": "Shapes",
    "address": "1.250",
    "legend": "WASH 04",
    "location": "Fixtures, 1.010",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "13",
    "fixture": "A.leda B-EYE K10",
    "mode": "Shapes",
    "address": "1.285",
    "legend": "WASH 05",
    "location": "Fixtures, 1.020",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "10"
  },
  {
    "userNo": "14",
    "fixture": "A.leda B-EYE K10",
    "mode": "Shapes",
    "address": "1.320",
    "legend": "WASH 06",
    "location": "Fixtures, 1.023",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "10"
  },
  {
    "userNo": "15",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.355",
    "legend": "RGB PAR 01",
    "location": "Fixtures, 1.032",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "16",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.363",
    "legend": "RGB PAR 02",
    "location": "Fixtures, 1.033",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "17",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.371",
    "legend": "RGB PAR 03",
    "location": "Fixtures, 1.034",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "18",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.379",
    "legend": "RGB PAR 04",
    "location": "Fixtures, 1.035",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "19",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.387",
    "legend": "RGB PAR 05",
    "location": "Fixtures, 1.036",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "20",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.395",
    "legend": "RGB PAR 06",
    "location": "Fixtures, 1.037",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "21",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.403",
    "legend": "RGB PAR 07",
    "location": "Fixtures, 1.038",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "22",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.411",
    "legend": "RGB PAR 08",
    "location": "Fixtures, 1.039",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "13"
  },
  {
    "userNo": "27",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.419",
    "legend": "RGB PAR 10",
    "location": "Fixtures, 1.047",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "28",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.427",
    "legend": "RGB PAR 11",
    "location": "Fixtures, 1.048",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "29",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.435",
    "legend": "RGB PAR 12",
    "location": "Fixtures, 1.049",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "30",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.443",
    "legend": "RGB PAR 13",
    "location": "Fixtures, 1.050",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "31",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.451",
    "legend": "RGB PAR 14",
    "location": "Fixtures, 1.051",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "32",
    "fixture": "Als 5403RGBW2 (User)",
    "mode": "Mode 1",
    "address": "1.459",
    "legend": "RGB PAR 15",
    "location": "Fixtures, 1.052",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "16"
  },
  {
    "userNo": "51",
    "fixture": "RGB, 4 DMX",
    "mode": "R,G,B,D",
    "address": "1.467",
    "legend": "RGB PAR 09",
    "location": "Fixtures, 1.046",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "14"
  },
  {
    "userNo": "52",
    "fixture": "RGB, 4 DMX",
    "mode": "R,G,B,D",
    "address": "1.475",
    "legend": "RGB PAR 16",
    "location": "Fixtures, 1.053",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "14"
  },
  {
    "userNo": "57",
    "fixture": "P600 CTO (User)",
    "mode": "Mode 1,5CH",
    "address": "2.1",
    "legend": "P600 CTO",
    "location": "Fixtures, 1.076",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "58",
    "fixture": "P600 CTO (User)",
    "mode": "Mode 1,5CH",
    "address": "2.6",
    "legend": "P600 CTO",
    "location": "Fixtures, 1.077",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "0"
  },
  {
    "userNo": "59",
    "fixture": "P600 CTO (User)",
    "mode": "Mode 1,5CH",
    "address": "2.11",
    "legend": "P600 CTO",
    "location": "Fixtures, 1.078",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "0"
  },
  {
    "userNo": "60",
    "fixture": "P600 CTO (User)",
    "mode": "Mode 1,5CH",
    "address": "2.16",
    "legend": "P600 CTO",
    "location": "Fixtures, 1.079",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "1"
  },
  {
    "userNo": "71",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "2.500",
    "legend": "Haze POWER",
    "location": "Fixtures, 1.043",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "1"
  },
  {
    "userNo": "72",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "2.501",
    "legend": "Haze Fan",
    "location": "Fixtures, 1.044",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "1"
  },
  {
    "userNo": "106",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.23",
    "legend": "Dim",
    "location": "Fixtures, 1.117",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "107",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.24",
    "legend": "Dim",
    "location": "Fixtures, 1.118",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "108",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.25",
    "legend": "Dim",
    "location": "Fixtures, 1.119",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "109",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.26",
    "legend": "Dim",
    "location": "Fixtures, 1.120",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "110",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.27",
    "legend": "Dim",
    "location": "Fixtures, 1.121",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "111",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.28",
    "legend": "Dim",
    "location": "Fixtures, 1.122",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "112",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.9",
    "legend": "Dim",
    "location": "Fixtures, 1.104",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "113",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.10",
    "legend": "Dim",
    "location": "Fixtures, 1.105",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "114",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.11",
    "legend": "Dim",
    "location": "Fixtures, 1.106",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "115",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.12",
    "legend": "Dim",
    "location": "Fixtures, 1.107",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "116",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.1",
    "legend": "Dim",
    "location": "Fixtures, 1.088",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "117",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.2",
    "legend": "Dim",
    "location": "Fixtures, 1.089",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "4"
  },
  {
    "userNo": "118",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.3",
    "legend": "Dim",
    "location": "Fixtures, 1.090",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "119",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.4",
    "legend": "Dim",
    "location": "Fixtures, 1.091",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "120",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.5",
    "legend": "Dim",
    "location": "Fixtures, 1.092",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "121",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.6",
    "legend": "Dim",
    "location": "Fixtures, 1.093",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "2"
  },
  {
    "userNo": "122",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.7",
    "legend": "Dim",
    "location": "Fixtures, 1.094",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "3"
  },
  {
    "userNo": "123",
    "fixture": "Dimmer",
    "mode": "Dimmer",
    "address": "3.8",
    "legend": "Dim",
    "location": "Fixtures, 1.095",
    "panInvert": "No",
    "tiltInvert": "No",
    "irisInvert": "No",
    "panOffset": "-",
    "tiltOffset": "-",
    "ptSwapped": "No",
    "frozen": "No",
    "notes": "",
    "itemsUsedIn": "3"
  }
];
